name: ecommerce_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/CairoBold.ttf
          weight: 700
        - asset: assets/fonts/CairoSemiBold.ttf
          weight: 600
